import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderShell from "@/components/layout/HeaderShell";
import Footer from "@/components/layout/Footer";
import NavigationLoader from "@/components/ui/NavigationLoader";
import HashScrollFix from "@/components/ui/HashScrollFix";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-slate-900">
        <HeaderShell />

        {/* Global utilities */}
        <NavigationLoader minMs={450} />
        <HashScrollFix extraGap={12} />

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
